apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-test-deployment
  labels:
    app: openshift-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift-test
  template:
    metadata:
      labels:
        app: openshift-test
    spec:
      containers:
      - name: openshift-test
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
